### ISSUE TITLE
Version 17.2 does not load using require('devextreme/dist/js/dx.all')

### ISSUE THREAD

**Issue by rodrigorodriguescosta** [DevExpress/devextreme-examples#32]
The latest version doesn't  work with Webpack like 17.1.8 !

`require('devextreme/dist/js/dx.all') ` doesn't load the DevExtreme with 17.2 version!

**Comment by dxvladislavvolkov** [comment]
Hello @rodrigorodriguescosta ,
We need more information to research the issue. Can you provide an example or a project where we can reproduce the problem?
In version 17, we made [breaking changes](https://www.devexpress.com/Support/Center/VersionHistory?TechnologyName=DevExtreme&PlatformName=AllPlatforms&ProductName=AllProducts&VersionHistoryItemsType=BreakingChanges&StartBuildName=17.2.3&EndBuildName=17.2.3&version-mode=single-mode#BC4148), and DevExtreme no longer depends on jQuery. Perhaps this problem is related to this

**Comment by rodrigorodriguescosta** [comment]
Can you provide an example or a project where we can reproduce the problem?
Sure, if you change only the version(to "devextreme": "^17.2.3") in package.json on this project [DevExtreme Jquery Webpack Sample](https://github.com/DevExpress/devextreme-examples/tree/17_1/webpack-jquery) the issue will occurs.


The issue is related to Webpack, we can't require the Devextreme using webpack

**Comment by dxvladislavvolkov** [comment]
We have updated the examples in branch 17.2. You can see them by switching to this branch.

**Comment by dxvladislavvolkov** [comment]
This issue was closed due to its inactive state. If you need further assistance, please open a new [Support Center](https://www.devexpress.com/Support/Center/Question/Create) ticket.
