### ISSUE TITLE
Where is the webpack-jquery-globalize example?

### ISSUE THREAD

**Issue by rodrigorodriguescosta** [DevExpress/devextreme-examples#33]
I can't use globalize with webpack + jquery and there is no example here, can you provide an example how to make it work?

**Comment by nightskylark** [comment]
Hi
Implementing this example is not in our immediate plans. Our team is concentrated on the functionality, provided in the Roadmap.
I believe that your scenario can be implemented based on the samples provided in our documentation. Refer to the following links.
https://js.devexpress.com/Documentation/Guide/Common/Modularity/Link_Modules/#Use_Webpack
https://js.devexpress.com/Documentation/Guide/Common/Localization/#Localize_Dates_Numbers_and_Currencies/Using_Globalize
https://js.devexpress.com/Documentation/Guide/Getting_Started/Widget_Basics_-_jQuery/Create_and_Configure_a_Widget/
If you experience issues adding Globalize to your app with Webpack, I recommend that you refer to public community resources such as Globalize or Webpack forums regarding this issue. Otherwise, you can use [Intl](https://js.devexpress.com/Documentation/Guide/Common/Localization/#Localize_Dates_Numbers_and_Currencies/Using_Intl) for localization.
